---
- name: Add Varnish APT signing key
  apt_key: 
    url: "https://repo.varnish-cache.org/GPG-key.txt"
    id: C4DEFFEB
    state: present

- name: Install APT HTTPS transport
  package:
    name: apt-transport-https
    state: present
    use: apt

- name: Add Varnish APT repository
  apt_repository: 
    repo: "deb https://repo.varnish-cache.org/{{ ansible_distribution|lower() }}/ {{ ansible_distribution_release }} varnish-{{varnish_version}}"
    update_cache: yes
    state: present
