---
- name: Test if using a phusion image
  stat:
    path: /sbin/my_init
  register: varnish_my_init_output

- name: Make sure /etc/service/varnish exists
  file:
    path: /etc/service/varnish
    state: directory
  when: varnish_my_init_output.stat.exists

- name: Install varnish at boot
  copy:
    src: varnish-init.sh
    dest: /etc/service/varnish/run
    mode: "a+x"
  when: varnish_my_init_output.stat.exists

- name: Stop service
  command: service varnish stop
  when: varnish_my_init_output.stat.exists
