---
- name: Create configuration directories
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ varnish_vcl_dir }}"
  tags:
    - conf
    - varnish

- name: Create secret key file
  shell: "echo \"{{ lookup('password', secret + '/credentials/varnish/secret chars=ascii_letters,digits,hexdigits') }}\" > {{ varnish_management_console_secret_file }}"

- name: Adapt to systemd
  lineinfile:
    dest: /etc/systemd/system/varnish.service
    follow: yes
    insertafter: "^\\[Service\\]$"
    state: present
    line: "EnvironmentFile=/etc/default/varnish"

- name: Configure Varnish
  template:
    src: varnish.conf.j2
    dest: "{{ varnish_conf_file }}"
  notify: Restart varnish
  tags:
    - conf
    - varnish

- name: Create vcl
  template:
    src: "{{ varnish_template_name + '.vcl.j2' }}"
    dest: "{{ varnish_vcl_dir }}/{{ varnish_template_name }}.vcl"
  notify: Restart varnish
  tags:
    - conf
    - varnish
