---
- include: prepare.yml

- include: configure-systemd.yml
  when: ansible_distribution_release == 'jessie' or ansible_distribution_release == 'vivid'

- include: configure.yml
  when: ansible_distribution_release != 'jessie' and ansible_distribution_release != 'vivid'

- include: vcl.yml
