---
- name: Create configuration directories
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ varnish_vcl_dir }}"

- name: Stat secret remote file
  stat: 
    path: "{{ varnish_management_console_secret_file }}" 
  register: secret_file
  changed_when: no

- name: Read secret remote file if it exists
  shell: cat {{ varnish_management_console_secret_file }}
  register: secret_remote
  when: secret_file.stat.exists
  changed_when: no
#  no_log: True

- name: Create/read secret local file
  shell: echo {{ lookup('password', secret + '/credentials/' + inventory_hostname + '/varnish/secret chars=ascii_letters,digits,hexdigits') }}
  register: secret_local
  changed_when: no
#  no_log: True

- name: Copy secret key file if needed
  shell: echo {{ secret_local.stdout }} > {{ varnish_management_console_secret_file }}
  when: secret_remote is not defined or (secret_remote is defined and secret_local.stdout != secret_remote.stdout)
#  no_log: True
