---
- name: Create backends include
  template:
    src: "drupsible/vcl_backend.j2"
    dest: "{{ varnish_vcl_dir }}/{{ varnish_app_name }}-backend.vcl"
  notify: 
    - Restart varnish

- name: Insert backends for the app in main acl
  blockinfile:
    dest: "{{ varnish_vcl_dir }}/drupsible.vcl"
    insertafter: '# block drupsible backend'
    marker: "# {mark} ANSIBLE MANAGED BLOCK BACKENDS {{ varnish_app_name }}"
    block: |
      include "{{ varnish_vcl_dir }}/{{ varnish_app_name }}-backend.vcl";
  notify: 
    - Restart varnish

- name: Create acl include
  template:
    src: "drupsible/vcl_acl.j2"
    dest: "{{ varnish_vcl_dir }}/{{ varnish_app_name }}-acl.vcl"
  notify: 
    - Restart varnish

- name: Insert a block for the app in main acl
  blockinfile:
    dest: "{{ varnish_vcl_dir }}/drupsible.vcl"
    insertafter: '# block drupsible acl'
    marker: "# {mark} ANSIBLE MANAGED BLOCK ACL {{ varnish_app_name }}"
    block: |
      include "{{ varnish_vcl_dir }}/{{ varnish_app_name }}-acl.vcl";
  notify: 
    - Restart varnish

- name: Create init include
  template:
    src: "drupsible/vcl_init.j2"
    dest: "{{ varnish_vcl_dir }}/{{ varnish_app_name }}-init.vcl"
  notify: 
    - Restart varnish

- name: Insert a block for the app in main vlc_init
  blockinfile:
    dest: "{{ varnish_vcl_dir }}/drupsible.vcl"
    insertafter: '# block drupsible init'
    marker: "# {mark} ANSIBLE MANAGED BLOCK INIT {{ varnish_app_name }}"
    block: |
      include "{{ varnish_vcl_dir }}/{{ varnish_app_name }}-init.vcl";
  notify: 
    - Restart varnish

- name: Create recv include
  template:
    src: "drupsible/vcl_recv.j2"
    dest: "{{ varnish_vcl_dir }}/{{ varnish_app_name }}-recv.vcl"
  notify: 
    - Restart varnish

- name: Insert a block for the app in main vlc_recv
  blockinfile:
    dest: "{{ varnish_vcl_dir }}/drupsible.vcl"
    insertafter: '# block drupsible recv'
    marker: "# {mark} ANSIBLE MANAGED BLOCK RECV {{ varnish_app_name }}"
    block: |
      if (req.http.Host ~ "{{ webdomain|default('') }}")
      {
        set req.backend_hint = {{ varnish_app_name }}_director.backend();
        include "{{ varnish_vcl_dir }}/{{ varnish_app_name }}-recv.vcl";
      }
  notify: 
    - Restart varnish
