---
- name: Create backends include
  template:
    src: "drupal/vcl_backend.j2"
    dest: "{{ varnish_vcl_dir }}/{{ app_name }}-backend.vcl"
  notify: 
    - Restart varnish

- name: Insert backends for the app in main acl
  blockinfile:
    dest: "{{ varnish_vcl_dir }}/drupsible.vcl"
    insertafter: '#block-backends'
    marker: "# {mark} ANSIBLE MANAGED BLOCK BACKENDS {{ app_name }}"
    block: |
      include "{{ varnish_vcl_dir }}/{{ app_name }}-backend.vcl";
  notify: 
    - Restart varnish

- name: Create acl include
  template:
    src: "drupal/vcl_acl.j2"
    dest: "{{ varnish_vcl_dir }}/{{ app_name }}-acl.vcl"
  notify: 
    - Restart varnish

- name: Insert a block for the app in main acl
  blockinfile:
    dest: "{{ varnish_vcl_dir }}/drupsible.vcl"
    insertbefore: '#block-acl-end'
    marker: "# {mark} ANSIBLE MANAGED BLOCK ACL {{ app_name }}"
    block: |
      include "{{ varnish_vcl_dir }}/{{ app_name }}-acl.vcl";
  notify: 
    - Restart varnish

- name: Create init include
  template:
    src: "drupal/vcl_init.j2"
    dest: "{{ varnish_vcl_dir }}/{{ app_name }}-init.vcl"
  notify: 
    - Restart varnish

- name: Insert a block for the app in main vlc_init
  blockinfile:
    dest: "{{ varnish_vcl_dir }}/drupsible.vcl"
    insertbefore: '#block-init-end'
    marker: "# {mark} ANSIBLE MANAGED BLOCK INIT {{ app_name }}"
    block: |
      include "{{ varnish_vcl_dir }}/{{ app_name }}-init.vcl";
  notify: 
    - Restart varnish

- name: Create recv include
  template:
    src: "drupal/vcl_recv.j2"
    dest: "{{ varnish_vcl_dir }}/{{ app_name }}-recv.vcl"
  notify: 
    - Restart varnish

- name: Insert a block for the app in main vlc_recv
  blockinfile:
    dest: "{{ varnish_vcl_dir }}/drupsible.vcl"
    insertbefore: '#block-recv-end'
    marker: "# {mark} ANSIBLE MANAGED BLOCK RECV {{ app_name }}"
    block: |
      if (req.http.Host ~ "{{ webdomain|default('') }}")
      {
        set req.backend_hint = {{ app_name }}_director.backend();
        include "{{ varnish_vcl_dir }}/{{ app_name }}-recv.vcl";
      }
  notify: 
    - Restart varnish
