---
# tasks file for adding Varnish modules compiled from source
- name: Install pre-requisites of varnish modules
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - varnish-modules
